//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medibox.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Medibox.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medibox.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string ButtonAbout {
            get {
                return ResourceManager.GetString("ButtonAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string ButtonAddMedicine {
            get {
                return ResourceManager.GetString("ButtonAddMedicine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        public static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        public static string ButtonDeleteMedicine {
            get {
                return ResourceManager.GetString("ButtonDeleteMedicine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit.
        /// </summary>
        public static string ButtonEditMedicine {
            get {
                return ResourceManager.GetString("ButtonEditMedicine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        public static string ButtonSave {
            get {
                return ResourceManager.GetString("ButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Your feedback here].
        /// </summary>
        public static string FeedbackBody {
            get {
                return ResourceManager.GetString("FeedbackBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry to hear you didn&apos;t want to rate Medibox..
        /// </summary>
        public static string FeedbackMessage1 {
            get {
                return ResourceManager.GetString("FeedbackMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no thanks.
        /// </summary>
        public static string FeedbackNo {
            get {
                return ResourceManager.GetString("FeedbackNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medibox Customer Feedback.
        /// </summary>
        public static string FeedbackSubject {
            get {
                return ResourceManager.GetString("FeedbackSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can we make it better?.
        /// </summary>
        public static string FeedbackTitle {
            get {
                return ResourceManager.GetString("FeedbackTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mobileapps@aturex.pl.
        /// </summary>
        public static string FeedbackTo {
            get {
                return ResourceManager.GetString("FeedbackTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to give feedback.
        /// </summary>
        public static string FeedbackYes {
            get {
                return ResourceManager.GetString("FeedbackYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type size of dose. 
        ///Example: 
        ///2 tablets 
        ///50 ml.
        /// </summary>
        public static string HelpDose {
            get {
                return ResourceManager.GetString("HelpDose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type the name of medicine.
        /// </summary>
        public static string HelpMedicineName {
            get {
                return ResourceManager.GetString("HelpMedicineName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type a note.
        /// </summary>
        public static string HelpNote {
            get {
                return ResourceManager.GetString("HelpNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the number of doses that you take in one day.
        /// </summary>
        public static string HelpNumberOfDosePerDay {
            get {
                return ResourceManager.GetString("HelpNumberOfDosePerDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set high priority to highlight the medicine.
        /// </summary>
        public static string HelpPriority {
            get {
                return ResourceManager.GetString("HelpPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set a reminder. The program will remind you when to take your next dose of medicine.
        /// </summary>
        public static string HelpReminder {
            get {
                return ResourceManager.GetString("HelpReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the day when you begin taking medicine.
        /// </summary>
        public static string HelpStartDate {
            get {
                return ResourceManager.GetString("HelpStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the time when you begin taking medicine.
        /// </summary>
        public static string HelpStartTime {
            get {
                return ResourceManager.GetString("HelpStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the day when to finish taking medicine.
        /// </summary>
        public static string HelpStopDate {
            get {
                return ResourceManager.GetString("HelpStopDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The end date must be greater than the start date.
        /// </summary>
        public static string MessageStopDateContent {
            get {
                return ResourceManager.GetString("MessageStopDateContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the end data.
        /// </summary>
        public static string MessageStopDateTitle {
            get {
                return ResourceManager.GetString("MessageStopDateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string PageAbout {
            get {
                return ResourceManager.GetString("PageAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to medicine.
        /// </summary>
        public static string PageMedication {
            get {
                return ResourceManager.GetString("PageMedication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new medicine.
        /// </summary>
        public static string PageNewMedicine {
            get {
                return ResourceManager.GetString("PageNewMedicine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to today.
        /// </summary>
        public static string PageToday {
            get {
                return ResourceManager.GetString("PageToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to medicine preview.
        /// </summary>
        public static string PageViewMedicine {
            get {
                return ResourceManager.GetString("PageViewMedicine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;d love you to rate our app 5 stars.
        /// </summary>
        public static string RatingMessage1 {
            get {
                return ResourceManager.GetString("RatingMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You look to be getting a lot of use out of our application!.
        /// </summary>
        public static string RatingMessage2 {
            get {
                return ResourceManager.GetString("RatingMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no thanks.
        /// </summary>
        public static string RatingNo {
            get {
                return ResourceManager.GetString("RatingNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enjoying Medibox?.
        /// </summary>
        public static string RatingTitle {
            get {
                return ResourceManager.GetString("RatingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rate 5 stars.
        /// </summary>
        public static string RatingYes {
            get {
                return ResourceManager.GetString("RatingYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Runtime Property Value.
        /// </summary>
        public static string SampleProperty {
            get {
                return ResourceManager.GetString("SampleProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ---------------------------------.
        /// </summary>
        public static string String {
            get {
                return ResourceManager.GetString("String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Name: {0}.
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Manufacturer: {1}.
        /// </summary>
        public static string String2 {
            get {
                return ResourceManager.GetString("String2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Firmware Version: {2}.
        /// </summary>
        public static string String3 {
            get {
                return ResourceManager.GetString("String3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Hardware Version: {3}.
        /// </summary>
        public static string String4 {
            get {
                return ResourceManager.GetString("String4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Version: {4}.
        /// </summary>
        public static string String5 {
            get {
                return ResourceManager.GetString("String5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ---------------------------------.
        /// </summary>
        public static string String6 {
            get {
                return ResourceManager.GetString("String6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tell us about your experience or suggest how we can make it even better..
        /// </summary>
        public static string String7 {
            get {
                return ResourceManager.GetString("String7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing us some love on the store helps us to continue to work on the app and make things even better!.
        /// </summary>
        public static string String8 {
            get {
                return ResourceManager.GetString("String8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why not give us a 5 star rating to show your appreciation?.
        /// </summary>
        public static string String9 {
            get {
                return ResourceManager.GetString("String9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author:.
        /// </summary>
        public static string TextAuthor {
            get {
                return ResourceManager.GetString("TextAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contact.
        /// </summary>
        public static string TextContact {
            get {
                return ResourceManager.GetString("TextContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily dose.
        /// </summary>
        public static string TextDailyDose {
            get {
                return ResourceManager.GetString("TextDailyDose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dose.
        /// </summary>
        public static string TextDose {
            get {
                return ResourceManager.GetString("TextDose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit or delete medicine.
        /// </summary>
        public static string TextEditOrDelete {
            get {
                return ResourceManager.GetString("TextEditOrDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact:.
        /// </summary>
        public static string TextEmail {
            get {
                return ResourceManager.GetString("TextEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I love Medibox.
        /// </summary>
        public static string TextEmailSubiect {
            get {
                return ResourceManager.GetString("TextEmailSubiect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of finish taking medicine passed.
        /// </summary>
        public static string TextEndDatePassed {
            get {
                return ResourceManager.GetString("TextEndDatePassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to quit the program?.
        /// </summary>
        public static string TextExit {
            get {
                return ResourceManager.GetString("TextExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to news :: tips :: information.
        /// </summary>
        public static string TextFacebookContent {
            get {
                return ResourceManager.GetString("TextFacebookContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TextFacebookInfo {
            get {
                return ResourceManager.GetString("TextFacebookInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medibox on Facebook.
        /// </summary>
        public static string TextFacebookTitle {
            get {
                return ResourceManager.GetString("TextFacebookTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The free version allows for the addition of 10 medicines.
        /// </summary>
        public static string TextFreeAddMedication {
            get {
                return ResourceManager.GetString("TextFreeAddMedication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HELP.
        /// </summary>
        public static string TextHelp {
            get {
                return ResourceManager.GetString("TextHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medibox application will facilitate your control over all medicines taken by you and your family.
        ///Medibox monitors the timing of medicines. Simply enter the name, size of dose and daily number of doses of medicines as well as the start date of its taking and the application will make you will always remember them..
        /// </summary>
        public static string TextInfo {
            get {
                return ResourceManager.GetString("TextInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medicine name.
        /// </summary>
        public static string TextMedicineName {
            get {
                return ResourceManager.GetString("TextMedicineName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press the Add button to add a medicine.
        /// </summary>
        public static string TextNoMedicines {
            get {
                return ResourceManager.GetString("TextNoMedicines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today isn&apos;t scheduled medications.
        /// </summary>
        public static string TextNoTasks {
            get {
                return ResourceManager.GetString("TextNoTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string TextNote {
            get {
                return ResourceManager.GetString("TextNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of doses per day.
        /// </summary>
        public static string TextNumberOfDosePerDay {
            get {
                return ResourceManager.GetString("TextNumberOfDosePerDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        public static string TextPriority {
            get {
                return ResourceManager.GetString("TextPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to high.
        /// </summary>
        public static string TextPriorityHigh {
            get {
                return ResourceManager.GetString("TextPriorityHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to normal.
        /// </summary>
        public static string TextPriorityNormal {
            get {
                return ResourceManager.GetString("TextPriorityNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rate me.
        /// </summary>
        public static string TextRateMe {
            get {
                return ResourceManager.GetString("TextRateMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminder.
        /// </summary>
        public static string TextReminder {
            get {
                return ResourceManager.GetString("TextReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to off.
        /// </summary>
        public static string TextReminderOff {
            get {
                return ResourceManager.GetString("TextReminderOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on.
        /// </summary>
        public static string TextReminderOn {
            get {
                return ResourceManager.GetString("TextReminderOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to store to buy full version.
        /// </summary>
        public static string TextRemoveAdContetnt {
            get {
                return ResourceManager.GetString("TextRemoveAdContetnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete this ad?.
        /// </summary>
        public static string TextRemoveAdTitle {
            get {
                return ResourceManager.GetString("TextRemoveAdTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT THE NUMBER OF DOSES PER DAY.
        /// </summary>
        public static string TextSelectNumberOfDosePerDay {
            get {
                return ResourceManager.GetString("TextSelectNumberOfDosePerDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single dose.
        /// </summary>
        public static string TextSingleDose {
            get {
                return ResourceManager.GetString("TextSingleDose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string TextStart {
            get {
                return ResourceManager.GetString("TextStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start on the date.
        /// </summary>
        public static string TextStartDate {
            get {
                return ResourceManager.GetString("TextStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start time.
        /// </summary>
        public static string TextStartTime {
            get {
                return ResourceManager.GetString("TextStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string TextStop {
            get {
                return ResourceManager.GetString("TextStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop on the date.
        /// </summary>
        public static string TextStopDate {
            get {
                return ResourceManager.GetString("TextStopDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to store.
        /// </summary>
        public static string TextStore {
            get {
                return ResourceManager.GetString("TextStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today&apos;s doses.
        /// </summary>
        public static string TextTodaysDoses {
            get {
                return ResourceManager.GetString("TextTodaysDoses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trial version allows for the addition of 5 medicines.
        ///Go to store to buy full version..
        /// </summary>
        public static string TextTrialContent {
            get {
                return ResourceManager.GetString("TextTrialContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trial.
        /// </summary>
        public static string TextTrialTitle {
            get {
                return ResourceManager.GetString("TextTrialTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to type the size of the dose.
        /// </summary>
        public static string TextTypeDose {
            get {
                return ResourceManager.GetString("TextTypeDose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to type the medicine name.
        /// </summary>
        public static string TextTypeMedicineName {
            get {
                return ResourceManager.GetString("TextTypeMedicineName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to type a note.
        /// </summary>
        public static string TextTypeNote {
            get {
                return ResourceManager.GetString("TextTypeNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating data.
        /// </summary>
        public static string TextUpdatingData {
            get {
                return ResourceManager.GetString("TextUpdatingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        public static string TextVersion {
            get {
                return ResourceManager.GetString("TextVersion", resourceCulture);
            }
        }
    }
}
